Bug Fixes

diff --git a/cryptdisksd b/cryptdisksd
--- a/cryptdisksd
+++ b/cryptdisksd
@@ -210,9 +210,9 @@ systemd_daemon()
 
 	# Check if there is a crypttab, log message if there isn't since everything we do is based on it.
 	if [[ ! -f ${conf[CRYPTTAB]} ]]; then
-		touch ${conf[CRYPTTAB]}
+		echo -e "#Crypt\t\t\t#Device\t\t\t\t#Passphrase\t\t#TRIM" >${conf[CRYPTTAB]}
 		do_log warning "${myname} crypttab not found" 
-		systemd-notify --pid=$$ --status="cryptdisksd: Crypttab (${conf[CRYPTTAB]}) not Found,"
+		systemd-notify --pid=$$ --status="cryptdisksd: Crypttab (${conf[CRYPTTAB]}) not Found"
 	fi
 
 	# Parse and load the configuration, exit if either fails.
@@ -729,21 +729,21 @@ do_daemon_cleanup()
 	fi
 
 	# Check the active crypts and add to active list if not already present.
-	local _crypt __crypt_arr _dev _pp _time __crypt 
+	local _crypt __crypt_arr _dev _pp _trim _time __crypt 
 	local _mnt_crypt="$(dmsetup ls --target crypt |cut -f1 |grep -vi "No devices found")"
 	for _crypt in ${_mnt_crypt}; do
 		if [[ -z "${active_mnt[${_crypt}]}" ]]; then
 			do_xcrypt_fromtab myname "${_crypt}"
+			[[ "$(lsblk -rD /dev/mapper/${_crypt} |head -n2 |tail -n1 |cut -d " " -f3)" == "0B" ]] && _trim=0 || _trim=1
 			if [[ ! -z "${__crypt_arr[0]}" ]]; then
 				_dev="${__crypt_arr[1]}"
 				_pp="$(do_eval_pp "${__crypt_arr[2]}")"
-				active_mnt[${_crypt}]="${_dev} ${_pp} ${__crypt_arr[3]} ${EPOCHREALTIME:0:-3}"
+				active_mnt[${_crypt}]="${_dev} ${_pp} ${_trim} ${EPOCHREALTIME:0:-3}"
 			else
 				_dev=/dev/"$(dmsetup deps ${_crypt} -o blkdevname |cut -d: -f2 |tr -d " ()")"
-				_pp="-"
-				active_mnt[${_crypt}]="${_dev} - 0 ${EPOCHREALTIME:0:-3}"
+				active_mnt[${_crypt}]="${_dev} - ${_trim} ${EPOCHREALTIME:0:-3}"
 			fi
-			do_log debug "${myname} found ${_dev} as ${_crypt} TRIM ${__crypt_arr[3]} passphrase ${_pp} adding to active list"
+			do_log debug "${myname} found ${_dev} as ${_crypt} TRIM ${_trim} passphrase ${_pp} adding to active list"
 		fi
 	done
 
@@ -752,20 +752,20 @@ do_daemon_cleanup()
 		for __crypt in ${_mnt_crypt}; do
 			[[ "${_crypt}" == "${__crypt}" ]] && continue 2
 		done
-		IFS=" " read -r _dev _pp __trim _time <<<"${active_mnt[${_crypt}]}"
-		do_log warning "${myname} ${_dev} as ${_crypt} TRIM ${__trim} passphrase ${_pp} mounted since $(do_timer date ${_time}) dissapeared"
+		IFS=" " read -r _dev _pp _trim _time <<<"${active_mnt[${_crypt}]}"
+		do_log warning "${myname} ${_dev} as ${_crypt} TRIM ${_trim} passphrase ${_pp} mounted since $(do_timer date ${_time}) dissapeared"
 		unset active_mnt[${_crypt}]
 	done
 
 	# If we have reloaded look up any managed crypts removed from crypttab and try to unmount them.
 	if [[ ! -z "${_tab_crypt}" ]]; then
 		for _crypt in ${!active_mnt[@]}; do
-			IFS=" " read -r _dev _pp __trim _time <<<"${active_mnt[${_crypt}]}"
+			IFS=" " read -r _dev _pp _trim _time <<<"${active_mnt[${_crypt}]}"
 			[[ "${_pp}" == "-" ]] && continue
 			for __crypt in ${_tab_crypt}; do
 				[[ "${_crypt}" == "${__crypt}" ]] && continue 2
 			done
-			do_log warning "${myname} ${_dev} as ${_crypt} TRIM ${__trim} passphrase ${_pp} mounted since $(do_timer date ${_time}) removed from crypttab"
+			do_log warning "${myname} ${_dev} as ${_crypt} TRIM ${_trim} passphrase ${_pp} mounted since $(do_timer date ${_time}) removed from crypttab"
 			do_daemon_unmount_crypt "${_crypt}"
 		done
 
@@ -781,6 +781,29 @@ do_daemon_cleanup()
 # [END OF MAIN DAEMON FUNCTIONS]
 
 # [BEGIN OF DAEMON CONTROL FUNCTIONS]
+do_daemon_notify()
+{
+	local _pid_ctrl=${msg_arr[3]} _cmd="${msg_arr[4],,}" _myname="daemon-notify (${BASHPID}):" _time_start=${EPOCHREALTIME:0:-3}
+	local _sock_ctrl="${conf[CRYPTDISKSDDIR]}/${MYNAME}-${_pid_ctrl}.sock"
+	do_log debug "${_myname} processing \"${msg_arr[@]:4}\""
+
+	# Process a command received from a control sub-process and notify about the result.
+	case ${_cmd} in
+		add)
+			local _add_crypt=${msg_arr[5]} _add_dev=${msg_arr[6]} _add_pp=${msg_arr[7]} _add_trim=${msg_arr[8]} _add_time=${EPOCHREALTIME:0:-3}
+			do_daemon_mount_crypt && echo "OK" >&${fd_ctrl[${_pid_ctrl}]} || echo "FAIL" >&${fd_ctrl[${_pid_ctrl}]}
+			local __passphrase="${passphrase}" __add_pp="${_add_pp}"; do_cache_pp daemon && cached_pp+="${_add_pp} "
+			do_log debug "${myname} active mounts: ${!active_mnt[@]}" ;;
+		del)
+			local _del_crypt=${msg_arr[5]}
+			do_daemon_unmount_crypt "${_del_crypt}" && echo "OK" >&${fd_ctrl[${_pid_ctrl}]} || echo "FAIL" >&${fd_ctrl[${_pid_ctrl}]}
+			do_log debug "${myname} active mounts: ${!active_mnt[@]}" ;;
+		*)
+			do_log debug "${_myname} received invalid notify command \"${msg_arr[@]:2}\"" ;;
+	esac
+	do_log debug2 "${_myname} processing \"${msg_arr[@]:4}\" took $(do_timer ${_time_start})s"
+	return 0
+}
 
 do_daemon_control()
 {
@@ -791,8 +814,10 @@ do_daemon_control()
 
 	# Set the FD redirections as per the loglevel.	
 	case ${conf[LOGLEVEL]} in
-		0|1|3)	local _fd_r="1>/dev/null 2>&1" ;;
-		2|4)	local _fd_r="1>&6 2>&1" ;;
+		0|1|3)
+			local _fd_r="1>/dev/null 2>&1" ;;
+		2|4)
+			local _fd_r="1>&6 2>&1" ;;
 	esac
 
 	# Process the command received and start the according control worker process.
@@ -836,7 +861,7 @@ daemon_control_status()
 	[[ -n "${bootconf[STORAGEPREFIX]}" ]] && __storageprefix="${bootconf[STORAGEPREFIX]}"
 	for __crypt in ${!active_mnt[@]}; do
 		__status=""
-		IFS=" " read -r __dev __pp __time __trim <<<"${active_mnt[${__crypt}]}"
+		IFS=" " read -r __dev __pp __trim __time <<<"${active_mnt[${__crypt}]}"
 		[[ "${__trim}" == "1" ]] && __trim="On" || __trim="Off"
 		if [[ "${__pp}" == "-" ]]; then
 			if [[ "${__crypt}" =~ ^${__storageprefix}[0-9]{1,2}$ ]]; then
@@ -1116,7 +1141,7 @@ do_control_add_crypt()
 do_control_add_crypttab()
 {
 	# Crypt should be added to crypttab. We should have a crypt, a dev and a passphrase name to use.
-	__add_crypt="${msg_arr[5]}" __add_dev="${msg_arr[6]}" __add_pp="$(do_eval_pp "${msg_arr[7]}")" __add_trim="${msg_arr[8]}"
+	__add_crypt="${msg_arr[5]}" __add_dev="${msg_arr[6]}" __add_pp="$(do_eval_pp "${msg_arr[7]}")" __add_trim="${msg_arr[8]}" __add=0 __res=""
 	
 	# Check if the crypt or device are already on the crypttab, error exit if so.
 	if do_xcrypt_fromtab __myname "${msg_arr[5]}" || do_xcrypt_fromtab __myname "${msg_arr[6]}"; then
@@ -1136,11 +1161,15 @@ do_control_add_crypttab()
 		do_find_dev && { echo -e "\r${RED}${BOLD}Both ${__add_crypt} and ${__add_dev} Are Valid Block Devices in \"${conf[BLOCKDEVSDIRS]}\" Bye Bye.${NOR}\r" >&${__socat[1]}; return 1; }
 		__add_crypt="${msg_arr[5]}" __add_dev="${__t}"
 	fi
+	if [[ ${__add_trim} -eq 1 && "$(lsblk -rD ${__add_dev} |head -n2 |tail -n1 |cut -d " " -f3)" == "0B" ]]; then
+		echo -ne "\r${YEL}${BOLD}${__add_dev} Does not Support TRIM.${NOR}\r"
+		__add_trim=0
+	fi
 
 	# Check if the crypt is already active and ask to continue with adding to crypttab if so.
 	if dmsetup info "${__add_crypt}" >/dev/null 2>&1; then
 		if [[ ${__confirm} -eq 1 ]]; then
-			local __add=1 __res=""
+			__add=1
 			echo -ne "\r${RED}${BOLD}${msg_arr[5]} Already Active, Add to Crypttab? (Y/n)${NOR}\r" >&${__socat[1]}
 			IFS= read -t${conf[USER_TIMEOUT]} -rsn1 -u ${__socat[0]} __res
 			echo -e "${BOLD}${__res}${NOR}\r" >&${__socat[1]}
@@ -1165,7 +1194,7 @@ do_control_add_crypttab()
 		fi
 		if [[ "${__res,,}" == "y" || "${__res}" == $'\r' || -z "${__res}" ]]; then
 			# Add the crypt to the crypttab and send reload signal to daemon.
-			echo -e "${__add_crypt}\t${__add_dev##*/}\t${__add_pp}" >> ${conf[CRYPTTAB]}
+			echo -e "${__add_crypt}\t${__add_dev##*/}\t${__add_pp}\t${__add_trim}" >> ${conf[CRYPTTAB]}
 			echo -e "\r${BOLD}${GRN}Added ${__add_dev} as ${__add_crypt} Passphrase ${__add_pp} TRIM ${__add_trim} to Crypttab${NOR}\r" >&${__socat[1]}
 			kill -SIGHUP ${pid_daemon}
 		fi
@@ -1273,14 +1302,21 @@ do_daemon_reader()
 	time_active=$(do_timer ${time_start})
 
 	case ${msg_arr[2]} in
-		started|passphrase|control) do_daemon_${msg_arr[2]} ;;
-		active)		reader_alive=0; do_log debug "${myname} reader (PID: ${pid_reader}) ping received" ;;
-		remove)		do_daemon_unmount_crypt "${msg_arr[3]}" ;;
-		add)		do_daemon_add_crypt "${msg_arr[3]}" "${msg_arr[4]}" "${msg_arr[5]}" "${msg_arr[6]}";;
-		cached)		cached_pp+="${msg_arr[3]} " ;;
-		reload) 	[[ ${confok} -eq 0 ]] && do_log debug "${myname} received reload request from reader while config is ok";
-					[[ -e /proc/self/fd/${fd_reader} ]] && exec {fd_reader}>&-; do_daemon_cleanup ;;
-		*)			do_log debug "${myname} received invalid message from reader \"${msg_arr[@]}\"" ;;
+		started|passphrase|control|notify)
+			do_daemon_${msg_arr[2]} ;;
+		active)
+			reader_alive=0; do_log debug "${myname} reader (PID: ${pid_reader}) ping received" ;;
+		remove)
+			do_daemon_unmount_crypt "${msg_arr[3]}" ;;
+		add)
+			do_daemon_add_crypt "${msg_arr[3]}" "${msg_arr[4]}" "${msg_arr[5]}" "${msg_arr[6]}";;
+		cached)
+			cached_pp+="${msg_arr[3]} " ;;
+		reload)
+			[[ ${confok} -eq 0 ]] && do_log debug "${myname} received reload request from reader while config is ok";
+			[[ -e /proc/self/fd/${fd_reader} ]] && exec {fd_reader}>&-; do_daemon_cleanup ;;
+		*)	
+			do_log debug "${myname} received invalid message from reader \"${msg_arr[@]}\"" ;;
 	esac
 
 	do_log debug2 "${myname} processing \"${msg}\" took $(do_timer ${_time_start})s total, waiting mounts for ${!waiting_mnt[@]}"
@@ -1290,8 +1326,8 @@ do_daemon_reader()
 do_daemon_add_crypt()
 {
 	# Received new crypt to mount from reader. If passphrase is given mount if not put on wait list.
-	local _add_crypt="$1" _add_dev="$2" _add_pp="$3" __add_trim="$4"
-	do_log debug "${myname} received ${_add_dev} as ${_add_crypt} TRIM ${__trim} passphrase ${_add_pp} from reader"
+	local _add_crypt="$1" _add_dev="$2" _add_pp="$3" _add_trim="$4"
+	do_log debug "${myname} received ${_add_dev} as ${_add_crypt} TRIM ${_add_trim} passphrase ${_add_pp} from reader"
 
 	if [[ ! -z "${passphrase}" ]]; then
 		# Passphrase received with crypt, mount immediately.
@@ -1305,18 +1341,18 @@ do_daemon_add_crypt()
 	# No passphrase received with crypt, add to waiting list
 	if [[ -z ${waiting_mnt[${_add_pp}]} ]]; then
 		# If the list is empty, add it.
-		waiting_mnt[${_add_pp}]="${_add_crypt} ${_add_dev} ${__add_trim} ${EPOCHREALTIME:0:-3}"
+		waiting_mnt[${_add_pp}]="${_add_crypt} ${_add_dev} ${_add_trim} ${EPOCHREALTIME:0:-3}"
 	else
 		# If the list is not empty go over it to see if there is a duplicate.
-		local _waiting_mnt="" _wait_crypt _wait_dev __wait_trim __wait_time
-		while IFS=" " read -r _wait_crypt _wait_dev __wait_trim _wait_time; do
+		local _waiting_mnt="" _wait_crypt _wait_dev _wait_trim _wait_time
+		while IFS=" " read -r _wait_crypt _wait_dev _wait_trim _wait_time; do
 			if [[ "${_add_crypt}" == "${_wait_crypt}" ]]; then
 				do_log warning "${myname} ${_add_crypt} already on waiting list, replacing"
 			else
-				_waiting_mnt+=$'\n'"${_wait_crypt} ${_wait_dev} ${__wait_trim} ${_wait_time}"
+				_waiting_mnt+=$'\n'"${_wait_crypt} ${_wait_dev} ${_wait_trim} ${_wait_time}"
 			fi
 		done <<<"${waiting_mnt[${_add_pp}]}"
-		waiting_mnt[${_add_pp}]="${_waiting_mnt}"$'\n'"${_add_crypt} ${_add_dev} ${__add_trim} ${EPOCHREALTIME:0:-3}"
+		waiting_mnt[${_add_pp}]="${_waiting_mnt}"$'\n'"${_add_crypt} ${_add_dev} ${_add_trim} ${EPOCHREALTIME:0:-3}"
 		waiting_mnt[${_add_pp}]="${waiting_mnt[${_add_pp}]:1}"
 	fi
 	do_log debug "${myname} added ${_add_crypt} to waiting list for ${_add_pp} \""${waiting_mnt[${_add_pp}]}"\""
@@ -1357,26 +1393,29 @@ do_daemon_mount_crypt()
 	# First check if the crypt is already mounted. If so, check if it's on the active list and add if not.	
 	if dmsetup info "${_add_crypt}" >/dev/null 2>&1; then
 		if [[ -z "${active_mnt[${_add_crypt}]}" ]]; then
+			[[ "$(lsblk -rD /dev/mapper/${_add_crypt} |head -n2 |tail -n1 |cut -d " " -f3)" == "0B" ]] && _add_trim=0
 			active_mnt[${_add_crypt}]="${_add_dev} ${_add_pp} ${_add_trim} ${_add_time}"
 			do_log debug "${myname} added ${_add_dev} as ${_add_crypt} TRIM ${_add_trim} passphrase ${_add_pp} to active list"
 			return 0
 		else
 			local __add_dev __add_pp __add_time __add_trim
 			IFS=" " read -r __add_dev __add_pp __add_trim __add_time <<< "${active_mnt[${_add_crypt}]}"
-			do_log debug "${myname} ${_add_dev} already active as ${_add_crypt} TRIM ${__add_trim} since $(do_timer date ${__add_time})"
+			do_log debug "${myname} ${_add_dev} already active as ${_add_crypt} TRIM ${_add_trim} since $(do_timer date ${__add_time})"
 			return 1
 		fi
 	else
-		local __trim=""
-		[[ ${_add_trim} -eq 1 ]] && trim="--allow-discards" 
-		if cryptsetup open --type plain "${__trim}" "${_add_dev}" "${_add_crypt}" <<<"${passphrase}"; then
+		if [[ "$(lsblk -rD ${_add_dev} |head -n2 |tail -n1 |cut -d " " -f3)" == "0B" ]]; then
+		       	_add_trim=0
+			do_log info "${myname} Requested TRIM for ${add_crypt} but device ${_add_dev} does not support it"
+		fi
+		if cryptsetup open --type plain $([[ ${_add_trim} -eq 1 ]] && echo "--allow-discards") "${_add_dev}" "${_add_crypt}" <<<"${passphrase}"; then
 			# Mounted, add to active list.
-			do_log info "${myname} mounted ${_add_dev} as ${_add_crypt} passphrase ${_dd_pp}"
-			do_log debug2 "${myname} mounting ${_add_dev} as ${_add_crypt} passphrase \"${passphrase}\" took $(do_timer ${_add_time})s"
-			active_mnt[${_add_crypt}]="${_add_dev} ${_add_pp} ${_add_time}"
+			do_log info "${myname} mounted ${_add_dev} as ${_add_crypt} TRIM ${_add_trim} passphrase ${_dd_pp}"
+			do_log debug2 "${myname} mounting ${_add_dev} as ${_add_crypt} TRIM ${_add_trim} passphrase \"${passphrase}\" took $(do_timer ${_add_time})s"
+			active_mnt[${_add_crypt}]="${_add_dev} ${_add_pp} ${_add_trim} ${_add_time}"
 			return 0
 		else
-			do_log error "${myname} error mounting ${_add_dev} as ${_add_crypt} after $(do_timer ${_add_time})s"
+			do_log error "${myname} error mounting ${_add_dev} as ${_add_crypt} TRIM ${_add_trim} after $(do_timer ${_add_time})s"
 			status=1
 			return 1
 		fi
@@ -1427,7 +1466,7 @@ do_xcrypt_fromtab()
 			do_log warning "${!1} incorrect crypttab entry ${__crypt_arr[@]}"
 			_status=2
 		else
-			[[ "${__crypt_arr[3]}" == "1" || ${__crypt_arr[3],,} == "y" ]] && __crypt_arr[3]=1 || __crypt_arr[3]=0
+			[[ "${__crypt_arr[3]}" == "1" || "${__crypt_arr[3],,}" == "y" || "${__crypt_arr[3],,}" == "yes" ]] && __crypt_arr[3]=1 || __crypt_arr[3]=0
 			return 0
 		fi
 	done
@@ -1727,10 +1766,14 @@ do_reader_fifo()
 	# Parse the command, the first element in the array is the command itself, the other elements the arguments to the command.
 	# From UDEV we will receive add and remove commands with one paramter only, the disk.
 	case ${__cmd} in
-		add|change)		do_reader_add_crypt ;;
-		remove)			do_reader_remove_crypt ;;
-		control)		do_reader_control ;;
-		*)			do_log debug "${__myname} received invalid command: \"${_cmd}\"" ;;
+		add|change)
+			do_reader_add_crypt;;
+		remove)
+			do_reader_remove_crypt;;
+		control|notify)
+			do_reader_control;;
+		*)
+			do_log debug "${__myname} received invalid command: \"${_cmd}\"";;
 	esac
 	__time_active="$(do_timer ${__time_start})"
 	do_log debug2 "${__myname} processing command \"${_cmd}\" took ${__time_active}s total"
@@ -1805,7 +1848,7 @@ do_reader_add_crypt()
 		if do_reader_check_ppwrk; then
 			# Worker is still active and valid, notify the reader about the crypt and continue reading the queue.
 			do_log debug "${__myname} passphrase worker (PID: ${_pid_ppwrk[${__add_pp}]}) for ${__add_pp} still valid"
-			do_reader_notify_daemon	"add ${__add_crypt} ${__add_dev} ${__add_pp}"
+			do_reader_notify_daemon	"add ${__add_crypt} ${__add_dev} ${__add_pp} ${__add_trim}"
 			exec {__fd_pp}>&-
 			return
 		fi
@@ -1970,8 +2013,8 @@ udev_reader_ppwrk()
    		IFS= read -t ${conf[QUEUE_TIMEOUT]} -u ${__fd_getpp}; 
 	done
 	[[ ${starting} -eq 0 ]] && IFS= read -t ${conf[QUEUE_TIMEOUT]} -u ${__fd_getpp}
-    [[ ${conf[LOGLEVEL]} -le 2 ]] && exec {__fd_querypp}< <(ppwrk_query_passphrase 1>/dev/null 2>&1)
-    [[ ${conf[LOGLEVEL]} -gt 2 ]] && exec {__fd_querypp}< <(ppwrk_query_passphrase 1>&6 2>&1)
+	[[ ${conf[LOGLEVEL]} -le 2 ]] && exec {__fd_querypp}< <(ppwrk_query_passphrase 1>/dev/null 2>&1)
+	[[ ${conf[LOGLEVEL]} -gt 2 ]] && exec {__fd_querypp}< <(ppwrk_query_passphrase 1>&6 2>&1)
 	__pid_querypp=$!
 	do_log debug "${__myname} started query passphrase worker (PID:${__pid_querypp})"
 
@@ -2320,8 +2363,8 @@ do_echo_use()
 			echo -e " Usage:\n\t${BOLD}${MYNAME} $1 [ -hct ] { crypt | device } || { -p passphrase crypt device }${NOR}\n\n"
 			echo -e " Options:\n\t${BOLD}-h${NOR}\t\tDisplay This Help Text"
 			echo -e "\t${BOLD}-c${NOR}\t\tAsk for Confirmation for Non-Crtitical Actions"
-			echo -e "\t${BOLD}-p {passphrase}${NOR}\tUse {passphrase} for Crypt\n\n"
-			echo -e "\t${BOLD}-t${NOR}\tEnable TRIM for Crypt\n\n"
+			echo -e "\t${BOLD}-p {passphrase}${NOR}\tUse {passphrase} for Crypt"
+			echo -e "\t${BOLD}-t${NOR}\t\tEnable TRIM for Crypt\n\n"
 			echo -e "The $1 Command Can Be Used it Two Ways.\nThe First ( ${BOLD}[ -c ] { crypt | device }${NOR} ) Will Add a Crypt or Device Which is Already on the Crypttab"
 			echo -e "The Second ( ${BOLD}[ -c ] { -p passphrase crypt device }${NOR} ) Will Add a crypt (and Corresponding Backing Device) to the Crypttab\nThe Option '${BOLD}-p passphrase${NOR}' Must Be Specified in the Second Case\n"
 			echo -e "The Options and Arguments Can Be Specified in any Order"
@@ -2415,6 +2458,7 @@ do_parse_opt()
 			[[ ${_cmd} -eq 0 || ! "${__command,,}" =~ ^(add|del|smart)$ ]] && do_echo_use "${__command}"
 			if [[ "${__command}" == "add" ]]; then
 				__add_trim=1
+				return 1
 			elif [[ "${__command}" == "del" ]]; then
 				[[  ${__crypttab} -eq 1 ]] && do_echo_use "${__command}"
 				__crypttab=1
