Default Config Fixes

diff --git a/cryptdisksd b/cryptdisksd
--- a/cryptdisksd
+++ b/cryptdisksd
@@ -164,7 +164,7 @@ do_init_conf()
 	conf[START_TIMEOUT]=$((conf[START_TIMEOUT]*60))
 	conf[PP_TIMEOUT]=$((conf[PP_TIMEOUT]*60))
 
-	systemdconf="$(cat ${CONF} |grep -ve "^\s*#")"
+	systemdconf="$(t_cat ${CONF} |grep -ve "^\s*#")"
 	return 0
 }
 
@@ -219,7 +219,7 @@ logwriter()
 do_log()
 {
 	# Send a message to the log writer, or to systemd if that fails.
-	if ! echo "$1 ${myname} ${@:2}" >&${fd_logwriter} && [[ "$1" =~ (warning|error) || ${conf[LOGLEVEL]} > 0 ]]; then
+	if ! echo "$1 ${myname} ${@:2}" >&${fd_logwriter} && [[ "$1" =~ (warning|error|info) || ${conf[LOGLEVEL]} > 0 ]]; then
 		echo "${myname} ${@:2}" >&${fd_journal}
 	fi
 	return 0
@@ -816,15 +816,13 @@ daemon_mount_sysimg()
 	if [[ ${res} -eq 0 ]]; then
 		do_log warning "mounting system image ${conf[SYSIMG]} on ${conf[ROOTDIR]}"
 		key="$(t_keyctl 1 request user "${conf[SYSTEMPP]}" @s)" && passphrase="$(t_keyctl 1 pipe "${key}")"
-		[[ -d /squashfs ]] || mkdir /squashfs || res=1
-		mount -t tmpfs tmpfs -o size="$(($(stat -c%s ${conf[SYSIMG]})+1))" /squashfs || res=1
 	fi
 	if [[ "${res}" -eq 0 && "${enc}" -eq 0 ]]; then
-		t_openssl aes-256-cbc -salt -d -pbkdf2 -in ${conf[SYSIMG]} -out /squashfs/${conf[SYSIMG]##*/} >/dev/null 2>&1 || res=1
-	elif [[ "${res}" -eq 0 ]]; then
-		t_cp ${conf[SYSIMG]} /squashfs/${conf[SYSIMG]##*/} >/dev/null 2>&1 || res=1
+		mv ${conf[SYSIMG]} ${conf[SYSIMG]}.enc
+		t_openssl aes-256-cbc -salt -d -pbkdf2 -in ${conf[SYSIMG]}.enc -out ${conf[SYSIMG]} >/dev/null 2>&1 || res=1
+		rm -f ${conf[SYSIMG]}.enc
 	fi
-	[[ "${res}" -eq 0 ]] && losetup $(losetup -f) /squashfs/${conf[SYSIMG]##*/} >/dev/null 2>&1 || res=1
+	[[ "${res}" -eq 0 ]] && losetup /dev/loop0 ${conf[SYSIMG]} >/dev/null 2>&1 || res=1
 	[[ "${res}" -ne 0 ]] && do_log error "failed to mount ${conf[SYSIMG]} on ${conf[ROOTDIR]}"
 	echo "${res}" |socat - UNIX-CONNECT:${sock}
 	[[ "$(</proc/${pid}/comm)" == "socat" ]] && sleep 0.01 && kill -SIGTERM ${pid} 2>/dev/null
